//! Issue #182: product-facing identity guard for `main`.
//!
//! Product-facing surfaces on `main` (the README introduction and the CLI's
//! user-visible description) must present MedScale as its own product, and
//! the records required by licenses must stay present. Historical records
//! (specs, evidence, planning matrices, PR text) are engineering provenance
//! and are deliberately not scanned.

use std::path::{Path, PathBuf};

fn repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn read(path: &str) -> String {
    std::fs::read_to_string(repo().join(path)).unwrap_or_else(|e| panic!("{path}: {e}"))
}

/// The README up to the engineering section is the product introduction.
fn readme_intro() -> String {
    let readme = read("README.md");
    let end = readme
        .find("## Working on MedScale")
        .expect("README keeps a separate engineering section");
    readme[..end].to_owned()
}

/// Phrases that must not appear in product-facing text (lowercase).
const STALE: &[&str] = &[
    "ui_visual_source = v0",
    "strategic donor",
    "capability floor",
    "generated by v0",
    "built with v0",
    "lorem ipsum",
    "create next app",
    "todo:",
];

fn assert_clean(surface: &str, text: &str) {
    let lower = text.to_lowercase();
    for phrase in STALE {
        assert!(
            !lower.contains(phrase),
            "{surface} contains stale product-facing text: {phrase:?}"
        );
    }
}

#[test]
fn product_facing_surfaces_present_medscale_first() {
    let intro = readme_intro();
    assert!(intro.starts_with("# MedScale"));
    assert!(intro.contains("engineering preview, synthetic data only"));
    assert!(intro.contains("not clinically validated"));
    assert_clean("README introduction", &intro);

    let cli = read("crates/medscale-cli/src/main.rs");
    let about: Vec<&str> = cli
        .lines()
        .filter(|l| l.trim_start().starts_with("about =") || l.contains("long_about ="))
        .collect();
    assert!(!about.is_empty(), "CLI keeps a user-visible description");
    for line in &about {
        assert!(line.contains("MedScale"), "CLI description names MedScale");
        assert_clean("CLI description", line);
    }
}

#[test]
fn bare_model_count_claims_stay_out_of_the_readme_introduction() {
    // A catalog listing is not an executable model (Spec 103).
    let intro = readme_intro().to_lowercase();
    for claim in ["2,266 models", "2266 models", "thousands of models"] {
        assert!(!intro.contains(claim), "bare model-count claim: {claim}");
    }
}

#[test]
fn records_required_by_licenses_are_present() {
    let root = repo();
    for path in [
        "LICENSE",
        "third_party/provenance",
        "assets/brand/fonts/FONT_NOTICE.md",
        "assets/brand/fonts/Inter-OFL.txt",
        "assets/brand/fonts/JetBrainsMono-OFL.txt",
        "assets/brand/fonts/InstrumentSans-OFL.txt",
        "docs/brand/PRE_RELEASE_IDENTITY_AND_PROVENANCE_AUDIT.md",
    ] {
        assert!(Path::new(&root.join(path)).exists(), "{path} must exist");
    }
}
